changes

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -31,7 +31,9 @@ apps:
     rubber-band-async:
         # command: python3 $SNAP/rubber_band_async.py
         # command: python $SNAP/rubber_band_async.py
-        command: $SNAP/rubber_band_async.py
+        # command: $SNAP/rubber_band_async.py
+        command: ls $SNAP
+
         # extensions: [gnome-3-34]
         extensions: [gnome-3-38]
         plugs: [unity7, audio-playback, home, network]
@@ -79,7 +81,7 @@ parts:
     build-packages:
       - python3.8-venv
       - python3.8-dev
-      - curl
+      - curl  # need this to grab pip
     build-environment:
       - SNAPCRAFT_PYTHON_INTERPRETER: python3.8
     override-build: |
@@ -90,17 +92,21 @@ parts:
       mkdir -p $SNAPCRAFT_PART_INSTALL/usr/include/
       ln -s /usr/include/python3.8 $SNAPCRAFT_PART_INSTALL/usr/include/python3.8
 
+      # WORKS but NOT NEEDED cos added curl to build-packages above
       # apt-get install --yes curl
       # curl -sS https://bootstrap.pypa.io/get-pip.py | sudo python3
 
-      which python3
-      which pip
-      echo lets look in /usr/bin
-      ls /usr/bin
-      echo lets look in usr/bin
-      ls usr/bin
+      # which python3  # /snap/gnome-3-38-2004-sdk/current/usr/bin/python3
+      # which pip    # NOT FOUND
+
+      # echo lets look in /usr/bin  <-- exists OK but does not list python
+      # ls /usr/bin
+
+      # echo lets look in usr/bin   <--- does not exist, FAILS
+      # ls usr/bin
+
       echo lets look in bin
-      ls bin
+      ls bin || true
 
       snapcraftctl build
 
